<%
  @path = "#{rubber_env.graylog_web_dir}/config/general.yml"
  graylog_server = rubber_instances.for_role("graylog_server").first
  webtools_server = rubber_instances.for_role("web_tools").first
%>

general:
  external_hostname: "<%= webtools_server.full_name %>:<%= rubber_env.web_tools_port %>" # Used for example to generate permalinks. Don't add 'http://' or trailing slashes.
  date_format: "%d.%m.%Y - %H:%M:%S" # http://ruby-doc.org/core/classes/Time.html#M000298 (strftime syntax)
  allow_deleting: false # Allowing deleting of messages negatively impacts performance
  allow_version_check: true # Enables manual (/versioncheck/index) and automatic (every 30min from overview page) version checking against graylog2.org via HTTP. 
  # custom_cookie_name: graylog2_staging1 # Set an own cookie name - Useful for multiple deployments on same host like example.org/staging1/graylog2, example.org/staging2/graylog2

# Settings for stream subscription emails. 
subscriptions:
  from: graylog2subscriptions@<%= rubber_env.domain %>
  subject: "[graylog2] Subscription"

# Settings for stream alarm emails.
streamalarms:
  from: graylog2alarms@<%= rubber_env.domain %>
  subject: "[graylog2] Stream alarm!"

hoptoad:
  enabled: false
  ssl: false
  api_key: 123
