<%
  @path = "#{rubber_env.graylog_web_dir}/config/mongoid.yml"
  graylog_server = rubber_instances.for_role("graylog_server").first
%>
defaults: &defaults
  host: localhost
  allow_dynamic_fields: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: graylog2_development

test:
  <<: *defaults
  database: graylog2_test

# set these environment variables on your prod server
production:
  host: <%= graylog_server.full_name %>
  port: 27017
  username:
  password:
  database: <%= rubber_env.graylog_mongo_database %>
